#!/bin/sh

UPLOADS_ROOT=/tmp/bismark-uploads
MAX_UPLOADS_BYTES=5000000
COLLECTION_INTERVAL_SECONDS=600

while true; do
    find $UPLOADS_ROOT -maxdepth 2 -type f -exec stat -t {} \; |
        awk '{ print $14, $2, $1 }' |
        sort -nr |
        awk "BEGIN { total = 0 } { total += \$2; if (total > $MAX_UPLOADS_BYTES) print \$3 }" |
        xargs -r rm
    sleep $COLLECTION_INTERVAL_SECONDS
done
