#!/bin/sh

UPLOADS_DIRECTORY=/tmp/bismark-uploads
MAX_UPLOADS_BYTES=5000000
COLLECTION_INTERVAL_SECONDS=600

while true; do
    find $UPLOADS_DIRECTORY -maxdepth 2 -type f -exec stat -c "%Z %s %n" {} \; |
        sort -nr |
        awk "BEGIN { total = 0 } { total += \$2; if (total > $MAX_UPLOADS_BYTES) print \$3 }" |
        xargs rm
    sleep $COLLECTION_INTERVAL_SECONDS
done
